"""Crew.ai Agents for Report Generation (Executor)"""

import logging
from app.config import llm

logger = logging.getLogger(__name__)


def get_compliance_analyst_agent():
    """
    Creates the Compliance Analyst agent for Executor.
    
    This agent analyzes compliance alerts and extracts key information
    for report generation.
    """
    from crew import Agent
    
    return Agent(
        role="Compliance Analyst",
        goal="Analyze compliance alerts and extract key information for report generation",
        backstory="Expert compliance analyst with 10+ years in fintech regulations",
        llm=llm,
        verbose=True,
    )


def get_company_data_fetcher_agent():
    """
    Creates the Company Data Fetcher agent for Executor.
    
    This agent retrieves company metadata and data locations for compliance reporting.
    In a real implementation, this would connect to actual data sources.
    """
    from crew import Agent
    
    return Agent(
        role="Company Data Fetcher",
        goal="Retrieve company metadata and data locations for compliance reporting",
        backstory="Data architect familiar with cloud infrastructure and data governance",
        llm=llm,
        verbose=True,
    )


def get_report_writer_agent():
    """
    Creates the Report Writer agent for Executor.
    
    This agent writes comprehensive, professional compliance reports in Markdown.
    """
    from crew import Agent
    
    return Agent(
        role="Compliance Report Writer",
        goal="Write comprehensive, professional compliance reports in Markdown",
        backstory="Technical writer specializing in compliance and regulatory documentation",
        llm=llm,
        verbose=True,
    )


def generate_mock_executor_report(alert, company_data: dict) -> str:
    """
    Generates a realistic mock Markdown report when API is unavailable.
    
    Args:
        alert: ComplianceAlert database object
        company_data: Dictionary with company information
    
    Returns:
        Markdown-formatted compliance report string
    """
    from datetime import datetime
    
    return f"""# Compliance Report

## Executive Summary

This report addresses the compliance alert: **{alert.summary}**

### Impact Assessment
- **Severity Level**: {alert.impact_json.get('impact', 'Medium')}
- **Status**: Action Required
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Company Details

- **Organization**: {company_data.get('company_name', 'N/A')}
- **User Base**: {company_data.get('user_count', 'N/A')} users
- **Data Locations**: {', '.join(company_data.get('data_locations', ['N/A']))}

## Compliance Findings

### Alert Details
{alert.summary}

### Required Actions
1. Review current compliance posture against new requirements
2. Update data residency and processing agreements if necessary
3. Conduct internal training for relevant teams
4. Document changes in compliance tracking system

### Risk Assessment
**Current Risk Level**: Medium-High

This alert requires immediate attention to ensure ongoing regulatory compliance and operational continuity.

### Recommendations

1. **Immediate (0-7 days)**
   - Conduct thorough compliance audit
   - Identify affected systems and processes
   - Begin stakeholder communication

2. **Short-term (1-2 weeks)**
   - Implement required policy changes
   - Update documentation
   - Deploy changes to production

3. **Follow-up (30+ days)**
   - Verify compliance through testing
   - Conduct regulatory reporting if required
   - Schedule follow-up audit

## Conclusion

This report has been automatically generated based on detected compliance alerts. 
All recommendations should be reviewed by your compliance team and implemented per your organization's change management procedures.

---
*Report generated by CompliOps Executor*
*Mock Report (No API Key)*
"""
