"""SQLAlchemy Database Models and Configuration"""

from datetime import datetime
from sqlalchemy import create_engine, Column, String, DateTime, Integer, JSON, Boolean
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# ============================================================================
# DATABASE SETUP
# ============================================================================

DATABASE_URL = "sqlite:///./complios.db"
engine = create_engine(DATABASE_URL, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# ============================================================================
# DATABASE MODELS
# ============================================================================

class User(Base):
    """User model for dummy auth."""
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    password_hash = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)


class ComplianceAlert(Base):
    """Stores compliance alerts detected by Watchtower."""
    __tablename__ = "compliance_alerts"
    
    id = Column(Integer, primary_key=True, index=True)
    source = Column(String, default="watchtower")
    summary = Column(String)
    impact_json = Column(JSON)  # Stores analysis as JSON
    action_required = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class GeneratedReport(Base):
    """Stores reports generated by the Executor."""
    __tablename__ = "generated_reports"
    
    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(Integer, index=True)
    status = Column(String, default="completed")  # completed, failed, in_progress
    title = Column(String)
    content_markdown = Column(String)  # Full Markdown report
    created_at = Column(DateTime, default=datetime.utcnow)


# Create all tables on startup
Base.metadata.create_all(bind=engine)
